package com.hallth.mapper;

import com.hallth.domain.CwUser;

public interface CwUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    int insert(CwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    int insertSelective(CwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    CwUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CwUser record);

    CwUser getUser(CwUser user);
}