package com.hallth.domain;

public class CwUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_company
     *
     * @mbggenerated
     */
    private String userCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_department
     *
     * @mbggenerated
     */
    private String userDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_user.user_status
     *
     * @mbggenerated
     */
    private Integer userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_id
     *
     * @return the value of cw_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_id
     *
     * @param userId the value for cw_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_name
     *
     * @return the value of cw_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_name
     *
     * @param userName the value for cw_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_password
     *
     * @return the value of cw_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_password
     *
     * @param userPassword the value for cw_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_company
     *
     * @return the value of cw_user.user_company
     *
     * @mbggenerated
     */
    public String getUserCompany() {
        return userCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_company
     *
     * @param userCompany the value for cw_user.user_company
     *
     * @mbggenerated
     */
    public void setUserCompany(String userCompany) {
        this.userCompany = userCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_department
     *
     * @return the value of cw_user.user_department
     *
     * @mbggenerated
     */
    public String getUserDepartment() {
        return userDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_department
     *
     * @param userDepartment the value for cw_user.user_department
     *
     * @mbggenerated
     */
    public void setUserDepartment(String userDepartment) {
        this.userDepartment = userDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_user.user_status
     *
     * @return the value of cw_user.user_status
     *
     * @mbggenerated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_user.user_status
     *
     * @param userStatus the value for cw_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
}